openapi: 3.0.0
info:
  title: Guestbook API
  version: 1.0.0
paths:
  /api/messages:
    get:
      x-yc-apigateway-integration:
        type: http
        url: https://bba198bg43om8m369k7q.containers.yandexcloud.net/api/messages
        method: GET
    post:
      x-yc-apigateway-integration:
        type: http
        url: https://bba198bg43om8m369k7q.containers.yandexcloud.net/api/messages
        method: POST
  /api/version:
    get:
      x-yc-apigateway-integration:
        type: http
        url: https://bba198bg43om8m369k7q.containers.yandexcloud.net/api/version
        method: GET
  /api/stats:
    get:
      x-yc-apigateway-integration:
        type: http
        url: https://bba198bg43om8m369k7q.containers.yandexcloud.net/api/stats
        method: GET
  /health:
    get:
      x-yc-apigateway-integration:
        type: http
        url: https://bba198bg43om8m369k7q.containers.yandexcloud.net/health
        method: GET